package com.piglatin.common.application.ports.input;

import com.piglatin.common.application.dto.ExecutionResponse;

import java.io.IOException;

/**
 * Entry port for the execution of C code generated by compiler
 * Allow verified the quatrain
 */
public interface ExecutionCCode {

    /** Compile the C code generated for the extarnal compilator
     * Execute the binary
     */
    ExecutionResponse execute (String cCode, String entryPoint);
    Process startInteractive(String cCode, String entryPoint, String outputDirectory) throws IOException;}
